"""message

Revision ID: 186050de5aab
Revises: feed87f6f16b
Create Date: 2024-08-16 14:27:40.182675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186050de5aab'
down_revision = 'feed87f6f16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
