"""Changing tables to rep data better

Revision ID: 2ce3332fd3e8
Revises: 48b9011b5fdd
Create Date: 2024-08-09 20:39:14.978127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce3332fd3e8'
down_revision = '48b9011b5fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('totalboxessold')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('totalboxessold')

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.drop_column('totalperbox')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalperbox', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalboxessold', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalboxessold', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
