"""fixing users

Revision ID: 6e7d8b26b785
Revises: c1751a7aca18
Create Date: 2024-08-19 20:30:08.266231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7d8b26b785'
down_revision = 'c1751a7aca18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gmailId', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('picture')
        batch_op.drop_column('gmailId')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
