"""added flavors and updated user and updated inventory

Revision ID: a8a8bad69b74
Revises: 2ce3332fd3e8
Create Date: 2024-08-13 15:09:33.443999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a8bad69b74'
down_revision = '2ce3332fd3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flavors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flavor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flavors'))
    )
    with op.batch_alter_table('inventorys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricePerBox', sa.Integer(), nullable=True))
        batch_op.drop_column('totalboxessold')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('password')

    with op.batch_alter_table('inventorys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalboxessold', sa.INTEGER(), nullable=True))
        batch_op.drop_column('pricePerBox')

    op.drop_table('flavors')
    # ### end Alembic commands ###
