"""message

Revision ID: fb112b07c4c9
Revises: 87e839e2df7b
Create Date: 2024-08-07 13:50:47.249510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb112b07c4c9'
down_revision = '87e839e2df7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventorys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flavor', sa.String(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('totalboxessold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventorys'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('totalboxessold', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flavor', sa.String(), nullable=True),
    sa.Column('box', sa.String(), nullable=True),
    sa.Column('priceperbox', sa.Integer(), nullable=True),
    sa.Column('totalboxessold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('scouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scouts', sa.String(), nullable=True),
    sa.Column('boxes', sa.Integer(), nullable=True),
    sa.Column('totalperbox', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_scouts_location_id_locations')),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_scouts_sale_id_sales')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scouts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scouts')
    op.drop_table('users')
    op.drop_table('sales')
    op.drop_table('locations')
    op.drop_table('inventorys')
    # ### end Alembic commands ###
